name: Joe Test
favicon: null
layout_spectrum: 0.5704533886164427
typography_spectrum: 0.0026613185182213783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6744180219247937
  lightness: 0.4573780579958111
  saturation: 0.6542040624190122
  rhythmicContrast: 0.14254843187518418
purpose: []
